### PR TITLE
Port 3.0 changes 

### PR DESCRIPTION
**Pull request by satyamakgec**

### CODE REVIEW

**Comment by maxsam4** [comment]
@satyamakgec There are no merge conflicts between `dev-3.0.0` and `dev-3.1.0`. Let's just directly merge them rather than using an intermediary `port-3.0-changes`.

**Review by VictorVicente — APPROVED** [review]
CLI files are OK

**Comment by satyamakgec** [comment]
@maxsam4 dev-3.1.0 is a protected branch, so we need the intermediary branch.

**Comment by maxsam4** [comment]
@satyamakgec https://github.com/PolymathNetwork/polymath-core/pull/741

**Comment by satyamakgec** [comment]
Closing in the favor of #741

**Pull request closed without merging**
