### PR TITLE
Migration script to 2.0.0

### PR DESCRIPTION
**Pull request by VictorVicente**
### Please check if the PR fulfills these requirements
- [x] The commit message follows our Submission guidelines

### What kind of change does this PR introduce? 
New upgrade script

### What is the current behavior? 
(You can also link to an open issue here)

### Does this PR introduce a breaking change?
No

### CODE REVIEW

**Comment by pabloruiz55** [comment]
@VictorVicente can you please add some step by step instructions on how to run this?

**Comment by VictorVicente** [comment]
@pabloruiz55 Instructions added on UPGRADE-PROCEDURES.MD

**Comment by pabloruiz55** [comment]
This is working fine. Asked Victor to also add a method to migrate just one specific ticker/token. Will merge when that's done.

**Comment by VictorVicente** [comment]
Done

**Review by pabloruiz55 — APPROVED** [review]

**Pull request merged**
