### PR TITLE
Migrate fix

### PR DESCRIPTION
**Pull request by maxsam4**
1) `npm i fs`
2) save private key in ./privKey
3) `truffle migrate --network kovan`

### CODE REVIEW

**Comment by maxsam4** [comment]
Nevermind
`Transaction gas price is too low. There is another transaction with same nonce in the queue. Try increasing the gas price or incrementing the nonce.`

**Comment by satyamakgec** [comment]
Why would we need that change? @maxsam4

**Comment by maxsam4** [comment]
@satyamakgec Because migration to Kovan are failing. Please refer to the slack channel for more info.

**Comment by maxsam4** [comment]
Build is passing, docs are failing. 
Coverage is failing though on all pr since morning.

**Comment by pabloruiz55** [comment]
Great job @maxsam4 ! I was able to test this and I can confirm I was able to deploy without any issues.

**Pull request merged**
