### PR TITLE
Update issue template

### PR DESCRIPTION
**Pull request by CPSTL**

### CODE REVIEW

**Review by thegostep — CHANGES_REQUESTED** [review]
need to adjust markdown formatting

**Comment by pabloruiz55** [comment]
@CPSTL / @sajclarke  please fix so I can merge it.

**Comment by pabloruiz55** [comment]
@CPSTL ?

**Comment by pabloruiz55** [comment]
@maxsam4 can you take a quick look at this and have @CPSTL wrap it up?

**Comment by maxsam4** [comment]
@CPSTL I don't think we need such detailed instructions in the Issue template. The template should only have heading to fill content under.

The instructions should go in contributing guidelines available on https://github.com/PolymathNetwork/polymath-core/blob/master/CONTRIBUTING.md

Also, consider adding an email for reporting critical bugs privately.

**Pull request closed without merging**
