### PR TITLE
An attempt to get docs script to run using solidoc

### PR DESCRIPTION
**Pull request by ross-rosario**
## Current docs issue
- solidity-docgen 0.1.x started complaining about function argument of type `mapping`, which had been introduced in v3.0.0.
- later versions of solidity-docgen might work, [but it can't handle dependencies yet](https://github.com/OpenZeppelin/solidity-docgen/issues/24) (eg OZ). Which makes it unusable for us.

## Proposed solution
- Use a simpler doc generator such as https://github.com/CYBRToken/solidoc
- The generator above relies on truffle ABI files. It doesn't even attempt to recompile the contract unless you tell it to. And then it can use `truffle compile`, honouring the local version of solc, which helps with avoiding version mismatches.
- However, unlike `solidity-docgen`, the proposed package is NOT built for docusauraus. For example, generated docs don't include the version eg `v3.0.0`.
- I had to fork `solidoc`, in order to support versions. Also, I've modified contracts markdown template a bit.
- Hopefully that fork could be the seed of our own document generator. There are no well maintained packages out there.
- Finally, I added `docs:generate` command, which is will generate documentation file, but won't attempt to push them to `polymath-developer-portal` repo. Could be useful for testing.

### CODE REVIEW

**Review by maxsam4 — COMMENTED** [review]
Looks good, thanks for doing this Remon!
Before we merge this, can you please remove `solidity-docgen` from dependencies?

**Comment by ross-rosario** [comment]
Thanks for checking it @maxsam4 . Honestly, I don't think it's ready for merging yet. Could you please try it locally and let me know what you think?

**Comment by maxsam4** [comment]
@remon-nashid I am getting this error when trying to generate docs
```
[1567164355824] INFO  (988 on max-GF63-8RC): Writing /home/max/Desktop/Ethereum/truffle 5/polymath-core/polymath-developer-portal/website/PolymathRegistry.md.
/home/max/Desktop/Ethereum/truffle 5/polymath-core/node_modules/solidoc/builders/super-builder.js:32
    builder.push(`[${baseContract.contractName}.${node.name}](${baseContract.contractName}.md#${node.name.toLowerCase()})`);
                                  ^

TypeError: Cannot read property 'contractName' of undefined
    at Object.build (/home/max/Desktop/Ethereum/truffle 5/polymath-core/node_modules/solidoc/builders/super-builder.js:32:35)
    at Object.serialize (/home/max/Desktop/Ethereum/truffle 5/polymath-core/node_modules/solidoc/serializers/function-serializer.js:55:33)
    at resolve (/home/max/Desktop/Ethereum/truffle 5/polymath-core/node_modules/solidoc/generator.js:18:29)
    at /home/max/Desktop/Ethereum/truffle 5/polymath-core/node_modules/require-all/index.js:56:38
    at Array.forEach (<anonymous>)
    at requireAll (/home/max/Desktop/Ethereum/truffle 5/polymath-core/node_modules/require-all/index.js:34:9)
    at serializeContract (/home/max/Desktop/Ethereum/truffle 5/polymath-core/node_modules/solidoc/generator.js:14:25)
    at Object.serialize (/home/max/Desktop/Ethereum/truffle 5/polymath-core/node_modules/solidoc/generator.js:31:22)
    at begin (/home/max/Desktop/Ethereum/truffle 5/polymath-core/node_modules/solidoc/cli.js:86:13)
    at Object.<anonymous> (/home/max/Desktop/Ethereum/truffle 5/polymath-core/node_modules/solidoc/cli.js:97:1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! polymath-core@3.0.0 docs:generate: `DOCS_PUBLISH=false scripts/docs.sh`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the polymath-core@3.0.0 docs:generate script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/max/.npm/_logs/2019-08-30T11_25_55_836Z-debug.log
```

**Comment by ross-rosario** [comment]
I had updated solidoc fork to allow ignoring certain pathes. Also modified `docs.sh` script to ignore `PolyOracle` contract. Docs generation should work now. @maxsam4 please try it one more time.

**Comment by maxsam4** [comment]
```
Generating the API documentation in branch v3.0.0
[1567515245789] ERROR (9855 on max-GF63-8RC): Invalid command /home/max/.nvm/versions/node/v8.12.0/bin/node /home/max/Desktop/Ethereum/truffle 5/polymath-core/node_modules/solidoc/cli.js /home/max/Desktop/Ethereum/truffle 5/polymath-core 3.0.0 true en 3.0.0 **/PolyOracle.json
/home/max/Desktop/Ethereum/truffle 5/polymath-core/node_modules/solidoc/cli.js:62
if(!config.pathToRoot) {
           ^

TypeError: Cannot read property 'pathToRoot' of undefined
    at Object.<anonymous> (/home/max/Desktop/Ethereum/truffle 5/polymath-core/node_modules/solidoc/cli.js:62:12)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
```

```
git pull
yarn install
npm run docs:generate
```

**Comment by ross-rosario** [comment]
Can't reproduce that here. Can you try one more time but with `yarn` this time?

**Comment by maxsam4** [comment]
same error.
Maybe yarn is not fetching the correct version of solidoc. I'll look into this later.

**Comment by ross-rosario** [comment]
My bad. I hadn't bumped the minor version of `PolymathNetwork/solidoc` so your yarn wasn't fetching the update. It's bumped to `1.0.5` now. I'd delete node_modules and re-install via `yarn` before testing again.

**Comment by satyamakgec** [comment]
@remon-nashid Let me know once it is ready for the review

**Comment by ross-rosario** [comment]
@satyamakgec it is ready for review :).

**Comment by satyamakgec** [comment]
@remon-nashid document generation is fine but because of some header problem, the developer portal is not working as it should be.

these are the warnings I get at the time of build 

Header field "" in /Users/satyamagrawal/polymath-core/polymath-developer-portal/website/versioned_docs/3.0.0/usingOraclize.md is not supported.
Header field "" in /Users/satyamagrawal/polymath-core/polymath-developer-portal/website/versioned_docs/3.0.0/Util.md is not supported.
Header field "" in /Users/satyamagrawal/polymath-core/polymath-developer-portal/website/versioned_docs/3.0.0/VersionUtils.md is not supported.
Header field "" in /Users/satyamagrawal/polymath-core/polymath-developer-portal/website/versioned_docs/3.0.0/VestingEscrowWallet.md is not supported.
Header field "" in /Users/satyamagrawal/polymath-core/polymath-developer-portal/website/versioned_docs/3.0.0/VestingEscrowWalletFactory.md is not supported.
Header field "" in /Users/satyamagrawal/polymath-core/polymath-developer-portal/website/versioned_docs/3.0.0/VestingEscrowWalletProxy.md is not supported.
Header field "" in /Users/satyamagrawal/polymath-core/polymath-developer-portal/website/versioned_docs/3.0.0/VestingEscrowWalletStorage.md is not supported.
Header field "" in /Users/satyamagrawal/polymath-core/polymath-developer-portal/website/versioned_docs/3.0.0/VolumeRestrictionLib.md is not supported.
Header field "" in /Users/satyamagrawal/polymath-core/polymath-developer-portal/website/versioned_docs/3.0.0/VolumeRestrictionTM.md is not supported.
Header field "" in /Users/satyamagrawal/polymath-core/polymath-developer-portal/website/versioned_docs/3.0.0/VolumeRestrictionTMFactory.md is not supported.

Above is just a comment to know that we have to fix the developer-portal code to make everything work.

**Review by satyamakgec — APPROVED** [review]

**Comment by ross-rosario** [comment]
@satyamakgec I pushed a fix to that latest warning.

I believe this is **the best** docs generation solution we could come up with. If we opt for using solidity-docgen, we'll need to fork it so that it supports dependencies  (basically refactor how contracts are being resolved) and then we'll be just on par with what solidoc generates. Additionally, latest solidity-docgen has departed docusaurus so it won't fit into our portal automatically, any more.

Let's merge this araic PR already :P.

**Pull request merged**
