### PR TITLE
Merge 2.1.0 updates and updates for 3.0.0

### PR DESCRIPTION
**Pull request by F-OBrien**
### Please check if the PR fulfills these requirements
- [x] The commit message follows our Submission guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

### What kind of change does this PR introduce? 
Merge dev-2.1.0 CLI updates
fixes & updates to token and registry interface files
fixed ST20Generator and update for 3.0.0
fixed Token Manager and update for 3.0.0

### What is the current behavior? 
CLI is currently broken in dev-3.0.0

### What is the new behavior?
some CLI's are now working

### Does this PR introduce a breaking change?
No

### CODE REVIEW

**Comment by VictorVicente** [comment]
This is great! Just let me know if you have any doubt. Once you think it's ready I'll test it if you want.

**Comment by F-OBrien** [comment]
@VictorVicente  I just plan to do bits every now and again in my spare time so if you had this planned for anytime soon feel review and merge as is. It will be better than the current broken version at least :smile:  

The ST20 Generator and STM are working now if you wanted to check them in your own time. Next I planned to work on the Transfer manager, STO manager and Investor portal. I intended to just getting them working again rather than adding any 3.0.0 features specifically or doing any major changes to the code.

**Comment by F-OBrien** [comment]
@VictorVicente This should now be ready for your review

**Comment by VictorVicente** [comment]
Hey @F-OBrien, I see you have been busy last days! Excellent job! It's amazing what you've done.
I'll spend some time testing and reviewing it so we can merge it soon.
Do you know what it is missing to finish? If you know there is some 3.0.0 feature pending, just tell me and I can work on it too.

**Comment by F-OBrien** [comment]
> Hey @F-OBrien, I see you have been busy last days! Excellent job! It's amazing what you've done.
> I'll spend some time testing and reviewing it so we can merge it soon.
> Do you know what it is missing to finish? If you know there is some 3.0.0 feature pending, just tell me and I can work on it too.

@VictorVicente There is still a lot missing. I mainly got everything working again but did add some functions. As there are a lot of changes in the pull request I didn't want to go adding too much additional until after it got merged.

I see @satyamakgec is updating the interface files in PR 682 so once he has them updated they can be removed from this PR.

If you've any questions or want me to make any changes let me know. Otherwise your free to work on these as you wish.

**Comment by VictorVicente** [comment]
I was just writing you to ask this merge. You are so fast 👍 
Once the CI finish, I'll merge this PR. Then I'll raise a new one with some other changes I was working on this week.
Thank you for your great collaboration @F-OBrien!

**Review by VictorVicente — APPROVED** [review]

**Pull request merged**
